name: chat_app_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_login: ^5.0.0
  freezed_annotation: ^2.4.4
  hydrated_bloc: ^10.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  logger: ^2.5.0
  pretty_dio_logger: ^1.4.0
  dio: ^5.8.0+1
  search_page: ^2.3.0
  dash_chat_2: ^0.0.21
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  freezed: ^2.5.8
  build_runner: ^2.4.14
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/.
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
